project_id = "wdvywhstuiywmtpgrznq"

[functions.vapid-public-key]
verify_jwt = false

[functions.scrape-notices]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.check-new-notices]
verify_jwt = false

[functions.proxy-download]
verify_jwt = false
